name: file_browser
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chunked_stream: ^1.4.1
  collection: ^1.17.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  get: ^4.1.4
  image: ^4.0.15
  path: ^1.8.2
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: